Hw7: Add message broker
GenesisEducationKyiv/hw1-se-school_2022-code-review-AnnFedorenko pull request #7
Opened 2022-10-07 21:28 UTC by AnnFedorenko

2022-10-08 17:51 UTC, platinum139 commented on log-consumer/cmd/log-consumer/main.go
> +	rmqClient, _ := rmq.NewRMQClient(rmq.RMQConfig{
You have unhandled error here. If an error happens while creating RabbitMQ Client, the client will be nil. But your program goes on and then you try to call some methods of the client. Your program will crash, which is not good.

2022-10-08 17:52 UTC, platinum139 commented on log-consumer/cmd/log-consumer/main.go
> +	defer rmqClient.CloseConnection()
You don't have to call defer 2 times. It should be called one time after successful rabbit mq client creation.

2022-10-08 17:54 UTC, platinum139 commented on rate-app/cmd/rate-api/app.go
> +	rmqCl, _ := logmb.NewRMQClient(logCfg)
Unhandled error here, same as in log-consumer.

2022-10-08 17:54 UTC, platinum139 commented on rate-app/cmd/rate-api/app.go
> +	rmqCl, _ := logmb.NewRMQClient(logCfg)
Also there is no closing connection for the client.

2022-10-08 18:00 UTC, platinum139 requested changes
In general, very good job!

2022-10-09 13:05 UTC, platinum139 approved these changes

2022-10-10 10:05 UTC, kerrrusha reviewed
well done but can be better

2022-10-10 10:05 UTC, kerrrusha commented on log-consumer/cmd/log-consumer/main.go
> +	defer rmqClient.CloseConnection()
Unhandled error
func (c *RMQClient) CloseConnection() error

2022-10-10 10:05 UTC, kerrrusha commented on rate-app/cmd/rate-api/app.go
> +	handler := handler.InitHandler(rateServ, emailServ, emailSendServ, rmqLogger)
Variable 'handler' collides with imported package name

2022-10-10 20:21 UTC, kerrrusha approved these changes
great job

2022-10-13 16:53 UTC, merged